version: "2.4"
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - "./dbfiles:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: ilc
